# Generated by Django 3.2.8 on 2022-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان سایت')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/slider', verbose_name='بارگذاری تصویر اسلایدر')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/ غیرفعال')),
            ],
            options={
                'verbose_name': 'تنظیمات بنر',
                'verbose_name_plural': 'مدیریت بنر',
            },
        ),
    ]
