# Generated by Django 3.2.8 on 2022-07-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topkala_banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.URLField(default=1, max_length=100, verbose_name='لینک'),
            preserve_default=False,
        ),
    ]
