# Generated by Django 3.2.8 on 2022-07-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topkala_banner', '0002_banner_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='active',
            field=models.BooleanField(verbose_name='فعال/ غیرفعال'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/banner', verbose_name='بارگذاری تصویر بنر'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='لینک'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=150, verbose_name='عنوان '),
        ),
    ]
