# Generated by Django 3.2.8 on 2022-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topkala_banner', '0003_auto_20220730_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsideBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/banner/aside-banner', verbose_name='بارگذاری تصویر بنر 272px*406px')),
            ],
        ),
    ]
