# Generated by Django 4.0.3 on 2022-04-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topkala_category', '0001_initial'),
        ('topkala_slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='categories',
            field=models.ManyToManyField(blank=True, to='topkala_category.productcategory', verbose_name='دسته بندی'),
        ),
    ]
