# Generated by Django 4.0.3 on 2022-04-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topkala_slider', '0002_slider_categories'),
        ('topkala_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='tags',
            field=models.ManyToManyField(blank=True, to='topkala_tag.tag', verbose_name='برچسب'),
        ),
    ]
